# Generated by Django 3.1 on 2020-09-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='platform',
            field=models.CharField(default='naver', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='webtoon_name',
            field=models.CharField(default='더 복서', max_length=100),
        ),
        migrations.AddField(
            model_name='fantasy',
            name='platform',
            field=models.CharField(default='naver', max_length=100),
        ),
        migrations.AddField(
            model_name='fantasy',
            name='webtoon_name',
            field=models.CharField(default='더 복서', max_length=100),
        ),
        migrations.AddField(
            model_name='romance',
            name='platform',
            field=models.CharField(default='naver', max_length=100),
        ),
        migrations.AddField(
            model_name='romance',
            name='webtoon_name',
            field=models.CharField(default='더 복서', max_length=100),
        ),
    ]
